#!/bin/bash
#======================================================================================
# Configure an instance of Ubuntu Linux to support Java development training courses.
#
# Arguments:
# (None)		
#
# Version: 1.2.0
# Date: 14 Aug 2014
# Author: Dave Nicolette
#======================================================================================
export INSTALL_DIR="$HOME/provision-java-dev-ubuntu"
export COMMON_DIR="provision-ubuntu-common"

git clone "git://github.com/neopragma/$COMMON_DIR"

"./$COMMON_DIR/install_build_support"
"./$COMMON_DIR/install_sublime_text_3"
"./$COMMON_DIR/install_curl"
"./$COMMON_DIR/install_aptitude"

echo
echo '============================================================='
echo 'Installing Microsoft TrueType fonts...'

"./$COMMON_DIR/install_mscorefonts"

echo
echo '============================================================='
echo 'Installing Java Development Kit...'

"./$COMMON_DIR/install_java8"

echo
echo '============================================================='
echo 'Installing Maven...'

"./$COMMON_DIR/install_maven"

# =============================================================
# Installing Eclipse...

"./$COMMON_DIR/install_eclipse_kepler"

echo
echo '============================================================='
echo 'Installing Ruby...'

"./$COMMON_DIR/install_ruby"

echo
echo '============================================================='
echo 'Installing ArgoUML...'

"./$COMMON_DIR/install_argouml"

echo
echo '============================================================='
echo 'Setting the desktop background image...'

mkdir -p "$HOME/.backgrounds"
cp -f java-background.png "$HOME/.backgrounds/."
gsettings set org.gnome.desktop.background picture-uri file:///home/student/.backgrounds/java-background.png

./verify


